### ISSUE TITLE
Profilo Ludovico

### ISSUE THREAD

**Issue by cloudify** [teamdigitale/teamdigitale.governo.it#325]
### Expected behavior

Profilo Ludovico esiste in inglese e italiano

### Actual behavior

Profilo Ludovico non esiste

### Steps to reproduce the behavior

Nella pagina [chi siamo](https://teamdigitale.governo.it/it/47-content.htm) e [About us](https://teamdigitale.governo.it/en/49-content.htm) deve esserci Ludovico nella lista

**Comment by sbronzolo** [comment]
@ludopoggi

**Comment by ludopoggi** [comment]
Ludovico Poggi - Comunicazione e relazioni istituzionali

Professionalmente sono nato e cresciuto in quel cantiere di idee che è lavoce.info, il think tank e watch dog della politica economica italiana fondato 15 anni fa da Tito Boeri. Lì ho compreso l’importanza di distinguere i fatti dai commenti e la capacità di giudicare il policy making a prescindere dall’appartenenza ideologica. Ho imparato a fare molte cose diverse nello stesso giorno e con pochi mezzi: ufficio stampa, editing, fundraising, social media, organizzazione di eventi. Lavoce mi ha insegnato un approccio learning by doing verso il web, conoscerne gli strumenti, dalle newsletter a Twitter, dal crowdfunding alle community. 

Durante i dieci anni a  Lavoce ho sperimentato altri lavori e in diversi campi: reporter per elezioni straniere (Grecia, Catalogna), caporedattore di una testata web di gender economy, curatore di un questionario qualitativo sull’utilizzo di internet nelle aziende lombarde (di fatto, il mio primo approccio ai temi di competenza del Team Digitale), consulente per la creazione e lo sviluppo di un sito della Pubblica Amministrazione (di fatto, il mio primo approccio con la PA), editor di un libro di proposte di governo in ambito politico economico.

È stato questo libro e il rapporto di amicizia negli anni successivi con l’autore, a strapparmi da una Milano in pieno Rinascimento e portarmi a Roma, da sempre la mia seconda città: nel febbraio 2016 sono diventato portavoce del Sottosegretario alla Presidenza del Consiglio con delega all’economia, al lavoro, povertà e ricerca Tommaso Nannicini.

Il passaggio a Palazzo Chigi è stata un’esperienza lavorativa incredibile da cui ho appreso, insieme molte altre cose, quanto un conto sia discutere e valutare la politica di un Governo un altro realizzarla.

Ho conosciuto Diego grazie a 18app il bonus cultura ai diciottenni. Ricordo bene le prime riunioni con lui, subentrato in corso a un progetto con varie complessità: il suo approccio manageriale e analitico, la sua capacità di risolvere i problemi un passo alla volta con metodo e senza condizionamenti ideologici: sono un fortunato testimone di quello che, spero, diventerà un giorno un cambio di paradigma nel modus operandi della Pubblica Amministrazione.

A dicembre, dopo la caduta del Governo Renzi - a cui era legato il mio mandato -, ho scoperto che Diego avrebbe continuato il suo lavoro con il Team per la Trasformazione Digitale e che alcune posizioni erano ancora aperte: tra queste, quella di Comunicazione e relazioni istituzionali. 










_Inizio mandato: 1 febbraio 2017
Fine mandato: 16 settembre 2018
Compenso su base annua: 67.000 euro
Registrazione in Corte dei Conti: 3 maggio 2017_

**Comment by cloudify** [comment]
@simonesurdi fai un check?

**Comment by simonesurdi** [comment]
@ludopoggi ho fatto delle correzioni di punteggiatura ed eliminato watch dog..che ne pensi? Me lo rigaurdi? cc @cloudify

**Comment by ludopoggi** [comment]
grazie @simonesurdi per me è ok @cloudify

**Comment by ludopoggi** [comment]
![foto bio](https://user-images.githubusercontent.com/25923669/31657681-5007b4f0-b32f-11e7-8285-bcff5af8231b.png)

qui foto @cloudify

**Comment by simonesurdi** [comment]
@ludopoggi ma non hai utilizzato il programmino contenuto nel doc di marisandra per trasformare la tua foto in cartoon?

**Comment by simonesurdi** [comment]
e la versione inglese?

**Comment by ludopoggi** [comment]
@simonesurdi mi ero dimenticato del programmino ora lo cerco. versione inglese in elaborazione

**Comment by ludopoggi** [comment]
![picturetopeople org-b524cc1d1e5290bb88e0d66554926d7985fd5481747797965d](https://user-images.githubusercontent.com/25923669/31658515-866e3e0e-b331-11e7-92d4-de8957649a57.jpg)

**Comment by simonesurdi** [comment]
ottimo @ludopoggi

**Comment by cloudify** [comment]
@ludopoggi mi servirebbe anche:

- [ ] utente twitter
- [ ] utente medium
- [ ] link a profilo linkedin

**Comment by ludopoggi** [comment]
@cloudify 
Twitter: @Ludo_poggi
Linkedin: ludovico-poggi-212a738/

**Comment by cloudify** [comment]
Con PR #335 abbiamo in `development` il profilo in Italiano di @ludopoggi

**Comment by cloudify** [comment]
@ludopoggi ci pensi tu alla traduzione all'inglese?

**Comment by ludopoggi** [comment]
sì @cloudify l'ho fatta volevo solo farla controllare

**Comment by ludopoggi** [comment]
I started my career at lavoce.info, an italian think tank and economic policy watch dog founded in 2002 by Tito Boeri. During this experience I learnt how to differentiate comments and facts, and used the latter to develop a solid assessment of the process of policy making, independently from the political parties that generated it. In this laboratory of ideas, where independence is of utmost importance, I managed to meet tight deadlines and covered different areas of the communication universe: press office, editing, fundraising, social media management and organization of events. I developed a learning-by-doing approach relying extensively on a wide range of instruments: internet, Twitter,(io li toglierei... in fin dei conti siamo nel 2017) a weekly newsletter, crowdfunding events and the community management.
 
Whilst working at lavoce.info, I have been a free-lance journalist: as an elections reporter in Greece and Spain, an editor in chief of a web-journal focused on gender economy and as a project manager for a proposal that evaluated the use of internet among enterprises located in Lombardy. I have also worked as a consultant for the development of a Public Administration’s websites and contributed to edit a book on economic policy proposals to the national government.
 
This experience, as well as the friendship that bore with Tommaso Nannicini, the curator of the book, would prompt me to move from Milan to Rome in February 2016. In the beautiful surroundings of the eternal city, I worked as a Director of Communications for Tommaso, then Undersecretary of State to the Prime Minister for Economic, Social and Research Policy. I soon realized the difference that lies between assessing government economic policy as an independent journalist and contributing to shape the same policies as an Undersecretary cabinet member.

 
After few months, thanks to one of these policies (18app, a platform that provides a cultural bonus to the young adults turning 18), I met Diego Piacentini, the Government Commissioner for the Digital Agenda. Since the first meeting I noticed his analytical and managerial approach to problems and his ability to move forward incrementally and without any pre-conceived ideology. I am still learning this useful method and one day I would hope the entire public administration could change its paradigm and adopt the same modus operandi.
 
In December 2016, in the aftermath of the Renzi’s government resignation, my contract expired and I discovered that Piacentini’s Digital Team was hiring: among the vacancies, I applied for the position in the Communications and institutional relations department.

**Comment by cloudify** [comment]
@ludopoggi qual'e' la traduzione di "Comunicazione e relazioni istituzionali" ?
